export default [
    {
        id: 1,
        image: 'https://via.placeholder.com/150',
        name: 'One',
        email: 'one@gmail.com',
        title: "Head Coach: Men's Basketball",
    },
    { id: 2, name: 'Two', email: 'two@gmail.com', title: 'Assistant Professor of Art' },
    { id: 3, name: 'Three', email: 'three@gmail.com', title: 'Faculty Fellow in Art' },
    { id: 4, name: 'Four', email: 'four@gmail.com', title: 'Assistant Professor of German' },
    {
        id: 5,
        image: 'https://via.placeholder.com/150',
        name: 'Five',
        email: 'five@gmail.com',
        title: 'Director of Academic Information Technology Services',
    },
    {
        id: 6,
        image: 'https://via.placeholder.com/150',
        name: 'Six',
        email: 'six@gmail.com',
        title: 'Communications Web Operations Manager',
    },
    {
        id: 7,
        image: 'https://via.placeholder.com/150',
        name: 'Seven',
        email: 'seven@gmail.com',
        title: '',
    },
    {
        id: 8,
        image: 'https://via.placeholder.com/150',
        name: 'Eight',
        email: 'eight@gmail.com',
        title: '',
    },
    {
        id: 9,
        image: 'https://via.placeholder.com/150',
        name: 'Nine',
        email: 'nine@gmail.com',
        title: 'Administrative Assistant, Department of Geology;',
    },
    {
        id: 10,
        image: 'https://via.placeholder.com/150',
        name: 'Ten',
        email: 'ten@gmail.com',
        title: 'Carter Professor of Mathematics',
    },
    {
        id: 11,
        image: 'https://via.placeholder.com/150',
        name: 'Eleven',
        email: 'eleven@gmail.com',
        title: 'Professor of Psychology',
    },
    {
        id: 12,
        image: 'https://via.placeholder.com/150',
        name: 'Twelve',
        email: 'twelve@gmail.com',
        title: 'Visiting Assistant Professor of Mathematics and Statistics',
    },
    {
        id: 13,
        name: 'Thirteen',
        email: 'thirteene@gmail.com',
        title: 'Communications Web/Multimedia Designer',
    },
    {
        id: 14,
        name: 'Fourteen',
        email: 'fourteen@gmail.com',
        title: 'Carter Professor of Mathematics',
    },
    { id: 15, name: 'Fifteen', email: 'fifteen@gmail.com', title: '' },
    {
        id: 16,
        image: 'https://via.placeholder.com/150',
        name: 'Sixteen',
        email: 'sixteen@gmail.com',
        title: 'Director of Creative Services',
    },
    {
        id: 17,
        name: 'Seventeen',
        email: 'seventeen@gmail.com',
        title: 'Teaching and Learning Applications Coordinator',
    },
    { id: 18, name: 'Eighteen', email: 'eighteen@gmail.com', title: 'Editorial Director' },
    {
        id: 19,
        name: 'Nineteen',
        email: 'ninteen@gmail.com',
        title: 'Carter Professor of Mathematics',
    },
    {
        id: 20,
        name: 'Twenty',
        email: 'twenty@gmail.com',
        title: 'Dean of Global Engagement; Associate Professor of German',
    },
    { id: 21, name: 'Twenty One', email: 'twenty_one@gmail.com', title: 'Professor of Psychology' },
    {
        id: 22,
        image: 'https://via.placeholder.com/150',
        name: 'Twenty Two',
        email: 'twenty_two@gmail.com',
        title: '',
    },
    {
        id: 23,
        image: 'https://via.placeholder.com/150',
        name: 'Twenty Three',
        email: 'twenty_three@gmail.com',
        title: '',
    },
    {
        id: 24,
        image: 'https://via.placeholder.com/150',
        name: 'Twenty Four',
        email: 'twenty_four@gmail.com',
        title: 'Carter Professor of Mathematics',
    },
    {
        id: 25,
        name: 'Twenty Five',
        email: 'twenty_five@gmail.com',
        title: 'Visiting Assistant Professor of Mathematics and Statistics',
    },
    {
        id: 26,
        name: 'Twenty Six',
        email: 'twenty_six@gmail.com',
        title: 'Professor of Mathematics and Statistics',
    },
];
